@startuml classes_classifier
set namespaceSeparator none
class "aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataLoader" as aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataLoader #aliceblue {
}
class "aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataset" as aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataset #aliceblue {
}
class "aiBoardGame.vision.xiangqiPieceClassifier.earlyStopping.EarlyStopping" as aiBoardGame.vision.xiangqiPieceClassifier.earlyStopping.EarlyStopping #aliceblue {
}
class "aiBoardGame.vision.xiangqiPieceClassifier.model.XiangqiPieceClassifier" as aiBoardGame.vision.xiangqiPieceClassifier.model.XiangqiPieceClassifier #aliceblue {
}
enum "aiBoardGame.vision.xiangqiPieceClassifier.utility.GenerateMode" as aiBoardGame.vision.xiangqiPieceClassifier.utility.GenerateMode #aliceblue {
}
class "torch.utils.data.dataloader.DataLoader" as torch.utils.data.dataloader.DataLoader #antiquewhite {
}
class "torch.utils.data.dataset.Dataset" as torch.utils.data.dataset.Dataset #antiquewhite {
}
class "torchvision.datasets.folder.DatasetFolder" as torchvision.datasets.folder.DatasetFolder #aquamarine {
}
class "torchvision.datasets.folder.ImageFolder" as torchvision.datasets.folder.ImageFolder #aquamarine {
}
class "torchvision.datasets.vision.VisionDataset" as torchvision.datasets.vision.VisionDataset #aquamarine {
}

aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataLoader --|> torch.utils.data.dataloader.DataLoader
aiBoardGame.vision.xiangqiPieceClassifier.dataset.XiangqiPieceDataset --|> torchvision.datasets.folder.ImageFolder
torchvision.datasets.folder.DatasetFolder --|> torchvision.datasets.vision.VisionDataset
torchvision.datasets.folder.ImageFolder --|> torchvision.datasets.folder.DatasetFolder
torchvision.datasets.vision.VisionDataset --|> torch.utils.data.dataset.Dataset
@enduml
