@startuml packages_package
set namespaceSeparator none
package "aiBoardGame" as aiBoardGame #aliceblue {
}
package "aiBoardGame.gameplay" as aiBoardGame.gameplay #antiquewhite {
}
package "aiBoardGame.gameplay.player" as aiBoardGame.gameplay.player #antiquewhite {
}
package "aiBoardGame.gameplay.utility" as aiBoardGame.gameplay.utility #antiquewhite {
}
package "aiBoardGame.gameplay.xiangqi" as aiBoardGame.gameplay.xiangqi #antiquewhite {
}
package "aiBoardGame.logic" as aiBoardGame.logic #aquamarine {
}
package "aiBoardGame.logic.engine" as aiBoardGame.logic.engine #aquamarine {
}
package "aiBoardGame.logic.engine.auxiliary" as aiBoardGame.logic.engine.auxiliary #aquamarine {
}
package "aiBoardGame.logic.engine.move" as aiBoardGame.logic.engine.move #aquamarine {
}
package "aiBoardGame.logic.engine.pieces" as aiBoardGame.logic.engine.pieces #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.advisor" as aiBoardGame.logic.engine.pieces.advisor #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.cannon" as aiBoardGame.logic.engine.pieces.cannon #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.chariot" as aiBoardGame.logic.engine.pieces.chariot #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.elephant" as aiBoardGame.logic.engine.pieces.elephant #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.general" as aiBoardGame.logic.engine.pieces.general #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.horse" as aiBoardGame.logic.engine.pieces.horse #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.piece" as aiBoardGame.logic.engine.pieces.piece #aquamarine {
}
package "aiBoardGame.logic.engine.pieces.soldier" as aiBoardGame.logic.engine.pieces.soldier #aquamarine {
}
package "aiBoardGame.logic.engine.replay" as aiBoardGame.logic.engine.replay #aquamarine {
}
package "aiBoardGame.logic.engine.utility" as aiBoardGame.logic.engine.utility #aquamarine {
}
package "aiBoardGame.logic.engine.xiangqiEngine" as aiBoardGame.logic.engine.xiangqiEngine #aquamarine {
}
package "aiBoardGame.logic.stockfish" as aiBoardGame.logic.stockfish #aquamarine {
}
package "aiBoardGame.logic.stockfish.fairyStockfish" as aiBoardGame.logic.stockfish.fairyStockfish #aquamarine {
}
package "aiBoardGame.main" as aiBoardGame.main #aliceblue {
}
package "aiBoardGame.robot" as aiBoardGame.robot #burlywood {
}
package "aiBoardGame.robot.robotArm" as aiBoardGame.robot.robotArm #burlywood {
}
package "aiBoardGame.view" as aiBoardGame.view #cadetblue {
}
package "aiBoardGame.view.utility" as aiBoardGame.view.utility #cadetblue {
}
package "aiBoardGame.view.xiangqiWindow" as aiBoardGame.view.xiangqiWindow #cadetblue {
}
package "aiBoardGame.vision" as aiBoardGame.vision #chartreuse {
}
package "aiBoardGame.vision.camera" as aiBoardGame.vision.camera #chartreuse {
}
package "aiBoardGame.vision.xiangqiPieceClassifier" as aiBoardGame.vision.xiangqiPieceClassifier #chartreuse {
}
package "aiBoardGame.vision.xiangqiPieceClassifier.dataset" as aiBoardGame.vision.xiangqiPieceClassifier.dataset #chartreuse {
}
package "aiBoardGame.vision.xiangqiPieceClassifier.earlyStopping" as aiBoardGame.vision.xiangqiPieceClassifier.earlyStopping #chartreuse {
}
package "aiBoardGame.vision.xiangqiPieceClassifier.model" as aiBoardGame.vision.xiangqiPieceClassifier.model #chartreuse {
}
package "aiBoardGame.vision.xiangqiPieceClassifier.utility" as aiBoardGame.vision.xiangqiPieceClassifier.utility #chartreuse {
}
aiBoardGame.gameplay.player --> aiBoardGame.gameplay.utility
aiBoardGame.gameplay.player --> aiBoardGame.logic
aiBoardGame.gameplay.player --> aiBoardGame.robot
aiBoardGame.gameplay.player --> aiBoardGame.vision
aiBoardGame.gameplay.xiangqi --> aiBoardGame.gameplay.player
aiBoardGame.gameplay.xiangqi --> aiBoardGame.gameplay.utility
aiBoardGame.gameplay.xiangqi --> aiBoardGame.logic
aiBoardGame.gameplay.xiangqi --> aiBoardGame.robot
aiBoardGame.gameplay.xiangqi --> aiBoardGame.vision
aiBoardGame.logic --> aiBoardGame.logic.engine
aiBoardGame.logic --> aiBoardGame.logic.stockfish
aiBoardGame.logic.engine --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine --> aiBoardGame.logic.engine.move
aiBoardGame.logic.engine --> aiBoardGame.logic.engine.utility
aiBoardGame.logic.engine --> aiBoardGame.logic.engine.xiangqiEngine
aiBoardGame.logic.engine.move --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.advisor
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.cannon
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.chariot
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.elephant
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.general
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.horse
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.piece
aiBoardGame.logic.engine.pieces --> aiBoardGame.logic.engine.pieces.soldier
aiBoardGame.logic.engine.pieces.advisor --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.advisor --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.cannon --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.cannon --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.chariot --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.chariot --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.elephant --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.elephant --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.general --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.general --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.horse --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.horse --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.pieces.piece --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.soldier --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.pieces.soldier --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.replay --> aiBoardGame.logic.engine.move
aiBoardGame.logic.engine.replay --> aiBoardGame.logic.engine.utility
aiBoardGame.logic.engine.replay --> aiBoardGame.logic.engine.xiangqiEngine
aiBoardGame.logic.engine.utility --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.utility --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.xiangqiEngine --> aiBoardGame.logic.engine.auxiliary
aiBoardGame.logic.engine.xiangqiEngine --> aiBoardGame.logic.engine.move
aiBoardGame.logic.engine.xiangqiEngine --> aiBoardGame.logic.engine.pieces
aiBoardGame.logic.engine.xiangqiEngine --> aiBoardGame.logic.engine.utility
aiBoardGame.logic.stockfish --> aiBoardGame.logic.stockfish.fairyStockfish
aiBoardGame.logic.stockfish.fairyStockfish --> aiBoardGame.logic.engine
aiBoardGame.main --> aiBoardGame.view.xiangqiWindow
aiBoardGame.robot --> aiBoardGame.robot.robotArm
aiBoardGame.view.xiangqiWindow --> aiBoardGame.gameplay
aiBoardGame.view.xiangqiWindow --> aiBoardGame.logic
aiBoardGame.view.xiangqiWindow --> aiBoardGame.logic.engine.utility
aiBoardGame.view.xiangqiWindow --> aiBoardGame.robot
aiBoardGame.view.xiangqiWindow --> aiBoardGame.view.utility
aiBoardGame.view.xiangqiWindow --> aiBoardGame.vision
aiBoardGame.vision --> aiBoardGame.vision.camera
aiBoardGame.vision --> aiBoardGame.vision.xiangqiPieceClassifier
aiBoardGame.vision.camera --> aiBoardGame.logic.engine
aiBoardGame.vision.xiangqiPieceClassifier --> aiBoardGame.vision.xiangqiPieceClassifier.dataset
aiBoardGame.vision.xiangqiPieceClassifier --> aiBoardGame.vision.xiangqiPieceClassifier.model
aiBoardGame.vision.xiangqiPieceClassifier.dataset --> aiBoardGame.logic.engine
aiBoardGame.vision.xiangqiPieceClassifier.dataset --> aiBoardGame.logic.engine.pieces
aiBoardGame.vision.xiangqiPieceClassifier.model --> aiBoardGame.logic.engine
aiBoardGame.vision.xiangqiPieceClassifier.model --> aiBoardGame.vision.xiangqiPieceClassifier.dataset
aiBoardGame.vision.xiangqiPieceClassifier.model --> aiBoardGame.vision.xiangqiPieceClassifier.earlyStopping
aiBoardGame.vision.xiangqiPieceClassifier.utility --> aiBoardGame.vision.camera
aiBoardGame.vision.xiangqiPieceClassifier.utility --> aiBoardGame.vision.xiangqiPieceClassifier.dataset
@enduml
