@startuml
interface CameraDevice as device1
component Camera {
    component Read
    component Undistort
    interface CameraDevice as device2
    interface RawImage
    interface UndistortedImage as undImg1
    portin DevicePort
    portout ImagePort as imgPortOut
}

device1 -> DevicePort
DevicePort -> device2
device2 -> Read
Read -> RawImage
RawImage -> Undistort
Undistort -> undImg1
undImg1 -> imgPortOut

interface UndistortedImage as undImg2
component BoardImageConverter {
    portin ImagePort as imgPortIn
    portout BoardImagePort as bip1
}
interface BoardImage as bImg1

imgPortOut --> undImg2
undImg2 --> imgPortIn
imgPortIn --> bip1
bip1 --> bImg1

component BoardPredictor {
    component SplitPieceImages
    component PredictBoardEntity
    component AssembleBoard
    interface BoardImage as bImg2
    interface PieceImage
    interface BoardEntity
    interface Board
    portin BoardImagePort as bip2
    portout BoardPort
}

bImg1 --> bip2
bip2 -> bImg2
bImg2 -> SplitPieceImages
SplitPieceImages -> PieceImage
PieceImage -> PredictBoardEntity
PredictBoardEntity -> BoardEntity
BoardEntity -> AssembleBoard
AssembleBoard -> Board
Board -> BoardPort
@enduml